# Generated by Django 3.2.4 on 2021-06-20 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='rec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rec', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='send',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send', to='customers.customer'),
        ),
    ]
